### ISSUE TITLE
SEGV_MAPERR error of some of wasm-spec-tests tests

### ISSUE THREAD

**Issue by penguinwu** [riscv-collab/v8#166]
**Describe the bug**
Several wasm-spec-tests test cases trigger the following errors:
```

```

**To Reproduce**
1. Build with `simulated.sim` options
2. Run test/program 
```
out/riscv64.sim/d8 --test test/wasm-spec-tests/tests/proposals/tail-call/skip-stack-guard-page.js --random-seed=1949695072 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-return-call --wasm-staging
```
3. See error
```
Received signal 11 SEGV_MAPERR 000000000000

==== C stack trace ===============================

 [0x55eb448a9707]
 [0x7f6c2bbf68a0]
 [0x55eb438e94ac]
 [0x55eb437b2863]
 [0x55eb437b2352]
 [0x55eb437a74ab]
 [0x55eb4378800d]
 [0x55eb43785c23]
 [0x55eb437fe466]
 [0x55eb437fe04a]
 [0x55eb438398dd]
 [0x55eb448aafad]
 [0x55eb448aef13]
 [0x55eb448a6cbd]
 [0x7f6c2bbeb6db]
 [0x7f6c2b156a3f]
[end of stack trace]
Segmentation fault (core dumped)
```
**Expected behavior**
No failure message means the test has passed

**Errors/Logs**
If applicable, copy/paste the errors or log messages here.

**Additional context**

The following tests fail w/ the same error message:
```
   'float_exprs': [SKIP],
   'skip-stack-guard-page': [SKIP],
   'proposals/tail-call/conversions': [SKIP],
   'proposals/tail-call/float_exprs': [SKIP],
   'proposals/tail-call/f64': [SKIP],
   'proposals/tail-call/f32': [SKIP],
   'proposals/tail-call/skip-stack-guard-page': [SKIP],
```

**Comment by luyahan** [comment]
0x7ffd4c1b4738: Unsupported instruction.
00000001       UNSUPPORTED
0x7ffd4c1b473c: Unsupported instruction.
00000085       UNSUPPORTED
0x7ffd4c1b4740: Unsupported instruction.
ffffffff       UNSUPPORTED
0x7ffd4c1b4744: Unsupported instruction.
ffffffff       UNSUPPORTED
0x7ffd4c1b4748: Unsupported instruction.
ffffffff       UNSUPPORTED
0x7ffd4c1b474c: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b474d: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b474e: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b474f: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b4750: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b4751: Unsupported instruction.
00000000       UNSUPPORTED
0x7ffd4c1b4752: Unsupported instruction.

**Comment by lazyparser** [comment]
@qjivy pls close it if not appear

**Comment by qjivy** [comment]
Retry this case on the riscv-sparkplug-dev branch with commit id bc90d62 , same error.

**Comment by lazyparser** [comment]
Fixed?

**Comment by luyahan** [comment]
Now this case test/wasm-spec-tests/tests/proposals/tail-call/skip-stack-guard-page.js does't exist.
