### ISSUE TITLE
Identify dependences of natively building V8 QEMU and on HiFive

### ISSUE THREAD

**Issue by penguinwu** [riscv-collab/v8#207]
Let's first identify if there are any build environment/tools dependencies to build V8 natively on QEMU and HiFive, and create subsequent issues if there are any.

**Comment by lazyparser** [comment]
I'll take a look.

the previous survey suggests that chromium/v8 pulls tons of binaries from google infrastructure, which might complex the native building. currently I am not optimistic.

**Comment by lazyparser** [comment]
Ji Qiu from the PLCT Lab would take a deeper look later.

**Comment by penguinwu** [comment]
@fw-brice Have we reached a conclusion on this one? Is there more that we need to find out. If not, please add a summary of what you found and close this one.

**Comment by lazyparser** [comment]
Already done by several different Linux distros.
