### ISSUE TITLE
[HIFIVE]cctest/test-heap-profiler/GlobalObjectNamepython2 failed

### ISSUE THREAD

**Issue by luyahan** [riscv-collab/v8#249]
**Describe the bug**

**To Reproduce**
1. Build with options `riscv64.native.release`
2. Run test/program ``
3. See error

**Expected behavior**

**Errors/Logs**
```
cctest/test-heap-profiler/GlobalObjectNamepython2: arena.c:770: get_free_list: Assertion `result->attached_threads == 0' failed.
```

**Additional context**

**Comment by lazyparser** [comment]
Is this bug still present or relevant?

**Comment by luyahan** [comment]
This test case be deleted.
