### ISSUE TITLE
Inefficient initialization of pointers

### ISSUE THREAD

**Issue by DrRezaYazdani1** [riscv-collab/v8#254]
Pointers are assumed to be 64 bits in V8. In practice they are 48 bits. The immediate value initialization of pointers generates 8 instructions where the optimum is 6.

li_constant(...) function called in "li(...)" in macro-assembler-riscv64.cc file, generates immediate pointer. We need a function li_ptr(...) to generate 6 instructions instead of 8 to replace li_constant(...) call.

The 48 bits generation with 6 instructions can be done with the following code sequence:

Intermediate constants extracted from the immediate value:
a6_0_5 = bits 0:6            // immediate 6 bits 
b11_6_16 = bits 6:11      // 11 bits
c12_17_28= bits 17:12   // 12 bits
d19_29_47 = bits 29:19 // 19 bits

Pseudo code generation:
rd<-(d19_29_47 + c12_17_28)      // 0:31, two instructions                         // lui & addi
rd<- (rd << 11)                            // open space                                        // shift
rd<- (rd | b11_6_16)                     // 0:42, include next 11 bits                   // or
rd<- (rd << 6)                              // Open space                                        // shift
rd<- (rd | a6_0_5)                         // 0:47, add next 6 bits                           // or

**Comment by lazyparser** [comment]
Hi @DrRezaYazdani1 

Are you still working on this issue, or can I close/reassign it?

**Comment by luyahan** [comment]
function li_ptr has been merged into upstream.
```
void Assembler::li_ptr(Register rd, int64_t imm) {
  // Initialize rd with an address
  // Pointers are 48 bits
  // 6 fixed instructions are generated
  DCHECK_EQ((imm & 0xfff0000000000000ll), 0);
  int64_t a6 = imm & 0x3f;                      // bits 0:5. 6 bits
  int64_t b11 = (imm >> 6) & 0x7ff;             // bits 6:11. 11 bits
  int64_t high_31 = (imm >> 17) & 0x7fffffff;   // 31 bits
  int64_t high_20 = ((high_31 + 0x800) >> 12);  // 19 bits
  int64_t low_12 = high_31 & 0xfff;             // 12 bits
  lui(rd, (int32_t)high_20);
  addi(rd, rd, low_12);  // 31 bits in rd.
  slli(rd, rd, 11);      // Space for next 11 bis
  ori(rd, rd, b11);      // 11 bits are put in. 42 bit in rd
  slli(rd, rd, 6);       // Space for next 6 bits
  ori(rd, rd, a6);       // 6 bits are put in. 48 bis in rd
}
```
