### ISSUE TITLE
Wishlist 2021 for V8 for RISC-V project: What goals we want to achieve by the end of 2021?

### ISSUE THREAD

**Issue by lazyparser** [riscv-collab/v8#366]
Please add comments here. All the wishes would be eventually appended into [community roadmap](https://github.com/v8-riscv/v8/wiki/Project-Roadmap)

A few wishes:
- Set up the performance tracking mechanism. (aka. the [code speed tracking infrastructure](https://github.com/riscv/riscv-code-speed-optimization/blob/main/projects/infrastructure-for-perf-tracking.adoc)
- Try to support RISC-V Vector Extension (V)
- Try to support B extension (B)
- Try to support P extension (DSP, Andes)
- Try to support C extension (ongoing work by @derekztu22 )
- Demo tensorflow.js on RISC-V
- Embrace nodejs community and support all the nodejs ecosystem running on RV64GC
- Speed up (blind say 5x) on RV64GC compared with the code we first upstreaming.
- resurrecting more than 10 new interns/contributors/graduates into our project.
- Hope we can see the Chromium running on PicoRio with V8 optimizations (RIOS Lab is working on this).

**Comment by lazyparser** [comment]
- Investigate on enabling V8 on hardware without floating-point extensions #110

**Comment by lazyparser** [comment]
- Investigate how to use LLVM to build V8 (#211)

**Comment by penguinwu** [comment]
More complete support for V8 WASM and performance (WASM is still under active development on V8 and currently there are still some test cases that are failing on our branch). 

I also feel that any push to ML workload/demo is likely to go through the WASM route. And WASM has the advantage of a defined SIMD IR for porting workloads for V extensions.

**Comment by penguinwu** [comment]
Would like to see at least one 3rd-party adoption of using v8-riscv to build their solutions. This also implies more time spent on servicing bug fixing or even feature requests from the users.

**Comment by lazyparser** [comment]
> Would like to see at least one 3rd-party adoption of using v8-riscv to build their solutions. This also implies more time spent on servicing bug fixing or even feature requests from the users.

There are already a few team interesting in the adoption of v8-riscv project. They are in the stage of internal testing and developing. Hopefully we can see at least 2 teams publicly use v8-riscv.

**Comment by lazyparser** [comment]
@qjivy after today's meeting:

- need to transfer this wishlist into roadmap.
- prioritize the bullets.
- (maybe) list who is/are working on each bullets.

**Comment by qjivy** [comment]
### 2021 V8 RISCV Roadmap-Items lists with priority from high to low
 
- Upstreaming(on going by Futurewei & RIOS Lab & PLCT)
- Demo and application launch
  - Demo tensorflow.js on RISC-V(todo)
  - Embrace node.js community and support all the node.js ecosystem running on RV64GC(todo)
  - Chromium running on PicoRio with V8(on going @RIOS lab)
- Performance (on going @PLCT)
  - Set up the performance tracking mechanism. 
  - Speed up (blind say 5x) on RV64GC compared with the code we first upstreaming 
- ISA-extension 
  - C (on going @ RIOS lab)
  - V (on going @ PLCT) 
  - B/P(todo)
- Ecosystem adaption
  - build v8 with LLVM(todo)
- Community develop and enlarge (on going @PLCT)
 - resurrecting more than 10 new interns/contributors/graduates into our project.

**Comment by lazyparser** [comment]
@qjivy good summary.

if all of us agree on this list, then @qjivy could create a new wiki page, or insert the 2021 roadmap on the top of https://github.com/v8-riscv/v8/wiki/Project-Roadmap

**Comment by chaoRIOS** [comment]
> ### 2021 V8 RISCV Roadmap-Items lists with priority from high to low
> * Upstreaming(on going by Futurewei & RIOS Lab & PLCT)
> * Demo and application launch
>   
>   * Demo tensorflow.js on RISC-V(todo)
>   * Embrace node.js community and support all the node.js ecosystem running on RV64GC(todo)
>   * Chromium running on PicoRio with V8(on going by RIOS lab)
> * Performance (on going by PLCT)
>   
>   * Set up the performance tracking mechanism.
>   * Speed up (blind say 5x) on RV64GC compared with the code we first upstreaming
> * ISA-extension
>   
>   * C (on going by RIOS lab)
>   * V (on going by PLCT)
>   * B/P(todo)
> * Ecosystem adaption
>   
>   * build v8 with LLVM(todo)
> * Community develop and enlarge (on going by PLCT)
>   
>   * resurrecting more than 10 new interns/contributors/graduates into our project.

Adding "WASM support, including atomic operations and trying out SIMD"

**Comment by lazyparser** [comment]
- [x]  Milestone 1: Upstreaming

**Comment by lazyparser** [comment]
Happy 2022!

We may publish a new roadmap for 2022 soon.
