### ISSUE TITLE
Review `Assembler::AdjustBaseAndOffset`

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#371]
There is a FIXME [here](https://github.com/v8-riscv/v8/blob/fc127d87bc4aa87e9729442d5ead953d01eb9112/src/codegen/riscv64/assembler-riscv64.cc#L2569) saying that there may be a more optimal implementation. This should be reviewed and optimized if possible, or else the FIXME should be removed.

**Comment by luyahan** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/2814563
