### ISSUE TITLE
Review use of t6 for indirect calls

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#372]
In some code copied from MIPS, it was noted that MIPS ABI requires that a certain register must be used for indirect calls. We chose to use `t6` in RISC-V, but are unclear about why that requirement existed in MIPS and if there is a similar requirement in RISC-V. See the FIXME and comment [here](https://github.com/v8-riscv/v8/blob/fc127d87bc4aa87e9729442d5ead953d01eb9112/src/codegen/riscv64/macro-assembler-riscv64.h#L29).

There is another FIXME [here](https://github.com/v8-riscv/v8/blob/fc127d87bc4aa87e9729442d5ead953d01eb9112/src/codegen/riscv64/macro-assembler-riscv64.cc#L2953) which is related to this.

**Comment by qjivy** [comment]
MIPS using this convention to ease debug in some breakpoint, the indirect call target can be guessed from the register info.

So V8 RISC-V backend, we done this  https://chromium-review.googlesource.com/c/v8/v8/+/2848100 to using t6 as target register to ease debug.
