### ISSUE TITLE
Review no_builtin_index

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#373]
Investigate [this FIXME](https://github.com/v8-riscv/v8/blob/fc127d87bc4aa87e9729442d5ead953d01eb9112/src/codegen/riscv64/macro-assembler-riscv64.cc#L4545):

```cpp
    // FIXME(RISCV64):on other arch, don't need no_builtin_index.
```

**Comment by luyahan** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/2970813/2/src/codegen/riscv64/macro-assembler-riscv64.cc
