### ISSUE TITLE
Review `kExprF32ConvertF64`

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#427]
From liftoff-assembler-ricv64.h:

```cpp
case kExprF32ConvertF64:
          fcvt_s_d(dst.fp(), src.fp());
          // FIXME (?): what if double cannot be represented by float?
          // Trunc_s_d(dst.gp(), src.fp(), kScratchReg);
          break;
```

**Comment by luyahan** [comment]
If a double value can't be represented by float, then it will be round accord Rounding Mode.
For example:
Rounding Mode is Round to Nearest, ties to Even
double is -3.4e+39, is will be convert to -inf by fcvt_s_d

**Comment by luyahan** [comment]
Use `fcvt_s_d(dst.fp(), src.fp());` is correct.  `Trunc_s_d` does't exited.
