### ISSUE TITLE
Review `Assembler::stop` implementation

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#428]
```cpp
void Assembler::stop(uint32_t code) {
  DCHECK_GT(code, kMaxWatchpointCode);
  DCHECK_LE(code, kMaxStopCode);
#if defined(V8_HOST_ARCH_RISCV64)
  // FIXME: does RISCV expect a special value?
  break_(0x54321);
#else  // V8_HOST_ARCH_RISCV64
  break_(code, true);
#endif
}
```

**Comment by luyahan** [comment]
See constants-mips.h:314
On MIPS Simulator breakpoints can have different codes:
- Breaks between 0 and kMaxWatchpointCode are treated as simple watchpoints,
  the simulator will run through them and print the registers.
- Breaks between kMaxWatchpointCode and kMaxStopCode are treated as stop()
  instructions (see Assembler::stop()).
- Breaks larger than kMaxStopCode are simple breaks, dropping you into the
  debugger.

On riscv ebreak only have one type

**Comment by luyahan** [comment]
riscv don't support stop instr. so we need this code in simulator.
