### ISSUE TITLE
Enable the build check and simulator testing on master branch

### ISSUE THREAD

**Issue by lazyparser** [riscv-collab/v8#445]
as the new workflow.

please be aware that the commits that pass he CI are candidates of the `riscv64` branch, and they should pass the qemu and hifive board testing before merged into the `riscv64` branch.

currently the qemu and board testing is semi-automatic. I'll try it later (and another issue for it).

**Comment by qjivy** [comment]
Already done for the upstreamed master https://ci.rvperf.org/view/V8/job/v8-upstream-master. 
Close.
