### ISSUE TITLE
RuntimeError: unreachable  in wasm-spec-tests/test/f32/f64.js 

### ISSUE THREAD

**Issue by luyahan** [riscv-collab/v8#460]
#### Command:
 `out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/f32.js --random-seed=1873986322 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner`
 `out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/f64.js --random-seed=1873986322 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner`
```
wasm-function[1]:0x68: RuntimeError: unreachable
RuntimeError: unreachable
    at run (<anonymous>:wasm-function[1]:0x68)
    at call (test/wasm-spec-tests/tests/f32.js:51:32)
    at test/wasm-spec-tests/tests/f32.js:7458:11
    at run (test/wasm-spec-tests/tests/f32.js:64:3)
    at test/wasm-spec-tests/tests/f32.js:7458:1
```

Maybe reason is result of a floating-point operator with  NaN  inputs is different bewteen wasm and js.
JS:
```
// According to JS ECMA specification, for floating-point round operations, if
// the input is NaN, +/-infinity, or +/-0, the same input is returned as the
// rounded result;
```
[wasm](https://webassembly.github.io/spec/core/exec/numerics.html#op-ffloor):
```
When the result of a floating-point operator other than fneg, fabs, or fcopysign is a NaN, then its sign is non-deterministic and the payload is computed as follows:

If the payload of all NaN inputs to the operator is canonical (including the case that there are no NaN inputs), then the payload of the output is canonical as well.

Otherwise the payload is picked non-deterministically among all arithmetic NaNs; that is, its most significant bit is 1 and all others are unspecified.
```

detail: `https://github.com/v8-riscv/v8/blob/riscv64/src/codegen/riscv64/macro-assembler-riscv64.cc#L1814`

**Comment by qjivy** [comment]
already fixed by #463.
close
