### ISSUE TITLE
inspector/debugger/wasm-gc-breakpoints: Unaligned read at 0xa979108c71 , pc=0x55e45a27fcb0

### ISSUE THREAD

**Issue by luyahan** [riscv-collab/v8#467]
=== inspector/debugger/wasm-gc-breakpoints ===
--- stdout ---
Tests GC object inspection.

Running test: test
Instantiating.
Waiting for wasm script (ignoring first non-wasm script).
Setting breakpoint at offset 107 on script wasm://wasm/22e4830a
Calling main()
Unaligned read at 0xa979108c71 , pc=0x55e45a27fcb0
  0x000055e45a27fcb0   0005b683       ld        a3, 0(a1)
sim>
```
Command: /b/s/w/ir/out/build/inspector-test /b/s/w/ir/test/inspector/protocol-test.js /b/s/w/ir/test/inspector/debugger/wasm-gc-breakpoints.js --random-seed=-976563914 --nohard-abort --testing-d8-test-runner --stress-incremental-marking --experimental-wasm-gc
```

**Comment by qjivy** [comment]
This case can pass test on the latest commit. 
[ re-enable it now ](https://chromium-review.googlesource.com/c/v8/v8/+/3295309)
