### ISSUE TITLE
RFC: we need to maintain the release version/branch of v8 for downstream projects, like nodejs

### ISSUE THREAD

**Issue by lazyparser** [riscv-collab/v8#486]
Current workflow does not consider release branch/version of v8.

After we begin to support nodejs, which uses release version of v8, we need to maintain multiple branches.

I put the burden of documenting new workflow on @qjivy 's shoulder :)

**Comment by qjivy** [comment]
Now we are able to maintain V8  just on upstream. So close this issue.
