### ISSUE TITLE
Test benchmark on d1 or unmatched

### ISSUE THREAD

**Issue by luyahan** [riscv-collab/v8#494]

**Comment by luyahan** [comment]
```
luyahan@RVBoards:~/v8$ python2.7 test/benchmarks/csuite/csuite.py sunspider compare out/riscv64.native.release/d8
Wrote /home/luyahan/v8/_results/master_sunspider_compare.
                               benchmark:    score |  master_ |      % |
===================================================+==========+========+
                       3d-cube-sunspider:    409.9 S    411.3 S    0.3 |
                      3d-morph-sunspider:    201.1 S    200.9 S        |
                   3d-raytrace-sunspider:    792.5 S    792.9 S        |
           access-binary-trees-sunspider:     97.4 S     97.1 S   -0.3 |
               access-fannkuch-sunspider:    234.1 S    234.2 S        |
                  access-nbody-sunspider:    144.9 S    146.2 S    0.9 |
                 access-nsieve-sunspider:    152.4 S    150.9 S   -1.0 |
      bitops-3bit-bits-in-byte-sunspider:     38.4 S     38.3 S   -0.3 |
           bitops-bits-in-byte-sunspider:     50.6 S     50.6 S        |
            bitops-bitwise-and-sunspider:     40.3 S     39.9 S   -1.0 |
            bitops-nsieve-bits-sunspider:    165.4 S    166.9 S    0.9 |
         controlflow-recursive-sunspider:     70.9 S     71.8 S    1.3 |
                    crypto-aes-sunspider:    350.8 S    354.5 S    1.1 |
                    crypto-md5-sunspider:    537.8 S    537.4 S        |
                   crypto-sha1-sunspider:    258.9 S    255.8 S   -1.2 |
             date-format-tofte-sunspider:    600.5 S    603.7 S    0.5 |
             date-format-xparb-sunspider:    534.0 S    536.3 S    0.4 |
                   math-cordic-sunspider:    125.2 S    125.6 S    0.3 |
             math-partial-sums-sunspider:    412.3 S    413.7 S    0.3 |
            math-spectral-norm-sunspider:     99.8 S     98.2 S   -1.6 |
                    regexp-dna-sunspider:    149.0 S    149.9 S    0.6 |
                 string-base64-sunspider:    532.9 S    534.1 S    0.2 |
                  string-fasta-sunspider:    244.6 S    246.6 S    0.8 |
               string-tagcloud-sunspider:    588.9 S    591.0 S    0.4 |
            string-unpack-code-sunspider:    473.5 S    473.6 S        |
         string-validate-input-sunspider:    365.6 S    364.5 S   -0.3 |
                               SunSpider:   7671.8 S   7685.8 S    0.2 |
---------------------------------------------------+----------+--------+
```

**Comment by luyahan** [comment]
Unmatched
```
bdWrote /home/yahan/v8/_results/master_kraken.                                                                          Run kraken again with compare mode to see results.                                                                      Wrote /home/yahan/v8/_results/master_kraken_compare.                                                                                                   benchmark:    score |  master_ |      % |
===================================================+==========+========+
                           ai-astar-orig:   3068.8 |   3061.3 |   -0.2 |
               audio-beat-detection-orig:   1484.2 S   1479.4 S   -0.3 |
                          audio-dft-orig:   3037.3 |   3036.1 |        |
                          audio-fft-orig:   1020.5 |   1020.4 |        |
                   audio-oscillator-orig:   1473.5 |   1473.4 |        |
              imaging-gaussian-blur-orig:   3647.7 |   3648.3 |        |
                   imaging-darkroom-orig:   2290.9 |   2290.7 |        |
                 imaging-desaturate-orig:   2701.9 |   2704.8 |    0.1 |
               json-parse-financial-orig:    568.7 |    568.3 |        |
           json-stringify-tinderbox-orig:    321.3 |    321.5 |        |
                stanford-crypto-aes-orig:   1356.1 |   1356.0 |        |
                stanford-crypto-ccm-orig:   1286.1 |   1286.8 |        |
             stanford-crypto-pbkdf2-orig:   1809.2 |   1809.2 |        |
   stanford-crypto-sha256-iterative-orig:    581.7 |    581.7 |        |
                                  Kraken:  24647.8 |  24637.8 |        |
---------------------------------------------------+----------+--------+
```

**Comment by qjivy** [comment]
Using Yahan's above statistics and add ARM CortexA53:


&nbsp; | arm64-CA53-1.4G-Android8.1.0-Chrome68.0.3440.91 | unmatch1.2G | D1 1G
-- | -- | -- | --
3d-cube-sunspider | 105.4 | 182.8 | 411.3
3d-morph-sunspider | 78.2 | 159.7 | 200.9
3d-raytrace-sunspider | 148.8 | 249.2 | 792.9
access-binary-trees-sunspider | 30.0 | 52.2 | 97.1
access-fannkuch-sunspider | 93.4 | 158.7 | 234.2
access-nbody-sunspider | 40.8 | 70.8 | 146.2
access-nsieve-sunspider | 59.4 | 102.4 | 150.9
bitops-3bit-bits-in-byte-sunspider | 13.7 | 25.4 | 38.3
bitops-bits-in-byte-sunspider | 25.2 | 33.7 | 50.6
bitops-bitwise-and-sunspider | 34.5 | 34.0 | 39.9
bitops-nsieve-bits-sunspider | 49.7 | 98.9 | 166.9
controlflow-recursive-sunspider | 31.8 | 50.4 | 71.8
crypto-aes-sunspider | 91.8 | 142.9 | 354.5
crypto-md5-sunspider | 64.5 | 119.2 | 537.4
crypto-sha1-sunspider | 81.1 | 139.0 | 255.8
date-format-tofte-sunspider | 120.2 | 189.1 | 603.7
date-format-xparb-sunspider | 97.3 | 177.1 | 536.3
math-cordic-sunspider | 48.1 | 78.2 | 125.6
math-partial-sums-sunspider | 198.7 | 296.5 | 413.7
math-spectral-norm-sunspider | 24.2 | 43.5 | 98.2
regexp-dna-sunspider | 32.0 | 135.4 | 149.9
string-base64-sunspider | 102.8 | 301.2 | 534.1
string-fasta-sunspider | 108.1 | 158.0 | 246.6
string-tagcloud-sunspider | 180.1 | 256.6 | 591.0
string-unpack-code-sunspider | 145.5 | 256.3 | 473.6
string-validate-input-sunspider | 81.6 | 153.9 | 364.5
total | 2086.9 | 3665.1 | 7685.9

**Comment by qjivy** [comment]
| |rv64-unmatched-debug（ms）      | rv64-unmatched-release（ms） | arm64-CA53-1.4G-Android8.1.0-Chrome68.0.3440.91  |
|------------------------------------|---------------------------------|--------------------------------------------------|-------|
| 3d-cube-sunspider                  | 2084.1                          | 167.4                                            | 105.4 |
| 3d-morph-sunspider                 | 1435.8                          | 155.8                                            | 78.2  |
| 3d-raytrace-sunspider              | 2842.1                          | 214.9                                            | 148.8 |
| access-binary-trees-sunspider      | 423.6                           | 48.5                                             | 30    |
| access-fannkuch-sunspider          | 1296.7                          | 138.6                                            | 93.4  |
| access-nbody-sunspider             | 591.5                           | 74.9                                             | 40.8  |
| access-nsieve-sunspider            | 875.6                           | 94.8                                             | 59.4  |
| bitops-3bit-bits-in-byte-sunspider | 242.2                           | 23                                               | 13.7  |
| bitops-bits-in-byte-sunspider      | 255.8                           | 31.1                                             | 25.2  |
| bitops-bitwise-and-sunspider       | 239.4                           | 23.3                                             | 34.5  |
| bitops-nsieve-bits-sunspider       | 1107.1                          | 94.2                                             | 49.7  |
| controlflow-recursive-sunspider    | 321.1                           | 43.3                                             | 31.8  |
| crypto-aes-sunspider               | 1467.8                          | 109.5                                            | 91.8  |
| crypto-md5-sunspider               | 1213.7                          | 96.1                                             | 64.5  |
| crypto-sha1-sunspider              | 1589.7                          | 135.3                                            | 81.1  |
| date-format-tofte-sunspider        | 1405.9                          | 174.9                                            | 120.2 |
| date-format-xparb-sunspider        | 2294.2                          | 187.1                                            | 97.3  |
| math-cordic-sunspider              | 636.6                           | 78.4                                             | 48.1  |
| math-partial-sums-sunspider        | 6903.8                          | 325.5                                            | 198.7 |
| math-spectral-norm-sunspider       | 421.5                           | 41.2                                             | 24.2  |
| regexp-dna-sunspider               | 237.1                           | 112.6                                            | 32    |
| string-base64-sunspider            | 2437.9                          | 196.5                                            | 102.8 |
| string-fasta-sunspider             | 1852.2                          | 175.7                                            | 108.1 |
| string-tagcloud-sunspider          | 2495.3                          | 285.3                                            | 180.1 |
| string-unpack-code-sunspider       | 2820.8                          | 299.5                                            | 145.5 |
| string-validate-input-sunspider    | 1666.4                          | 165.6                                            | 81.6  |


v8 commit: 
commit 83c3489d3d23ff9a0f8374f6f39f73d3d8a92d37 (HEAD, origin/main, origin/HEAD)  
Author: Andreas Haas <ahaas@chromium.org>  
Date:   Tue Nov 16 18:36:36 2021 +0100  
[wasm] Cleanup Callback removal

**Comment by luyahan** [comment]
```
Wrote /home/luyahan/v8/_results/master_kraken_compare.
                               benchmark:    score |  master_ |      % |
===================================================+==========+========+
                           ai-astar-orig:   3048.5 |   3046.1 |        |
               audio-beat-detection-orig:   1374.6 S   1380.0 S    0.4 |
                          audio-dft-orig:   3220.4 |   3213.9 |   -0.2 |
                          audio-fft-orig:    935.1 |    934.9 |        |
                   audio-oscillator-orig:   1379.9 |   1378.5 |   -0.1 |
              imaging-gaussian-blur-orig:   2542.9 S   2543.5 S        |
                   imaging-darkroom-orig:   2079.5 |   2074.9 |   -0.2 |
                 imaging-desaturate-orig:   3061.3 |   3063.1 |        |
               json-parse-financial-orig:    467.8 |    467.4 S        |
           json-stringify-tinderbox-orig:    284.1 |    284.7 |    0.2 |
                stanford-crypto-aes-orig:   1297.1 |   1295.7 |   -0.1 |
                stanford-crypto-ccm-orig:   1143.9 S   1141.2 S   -0.2 |
             stanford-crypto-pbkdf2-orig:   1667.3 |   1666.3 |        |
   stanford-crypto-sha256-iterative-orig:    516.5 |    515.6 |   -0.2 |
                                  Kraken:  23018.9 |  23005.7 |        |
---------------------------------------------------+----------+--------+
```

**Comment by luyahan** [comment]
```
Richards: 2040
DeltaBlue: 2804
Crypto: 2859
RayTrace: 1526
EarleyBoyer: 1533
RegExp: 229
Splay: 932
SplayLatency: 3791
NavierStokes: 1975
PdfJS: 1045
Mandreel: 1396
MandreelLatency: 1490
Gameboy: 1639
CodeLoad: 2593
Box2D: 1074
zlib: 4112
Typescript: 1707
----
```

**Comment by luyahan** [comment]
```
                               benchmark:    score |  master_ |      % |
===================================================+==========+========+
                       3d-cube-sunspider:    166.8 |    167.5 |    0.4 |
                      3d-morph-sunspider:    143.8 |    144.1 S    0.2 |
                   3d-raytrace-sunspider:    207.3 |    207.7 |    0.2 |
           access-binary-trees-sunspider:     51.4 |     51.6 |    0.4 |
               access-fannkuch-sunspider:    135.7 |    135.8 |        |
                  access-nbody-sunspider:     74.6 |     74.8 |    0.3 |
                 access-nsieve-sunspider:     96.3 |     96.6 |    0.3 |
      bitops-3bit-bits-in-byte-sunspider:     22.2 S     22.2 S        |
           bitops-bits-in-byte-sunspider:     31.0 S     31.1 S    0.3 |
            bitops-bitwise-and-sunspider:     23.4 S     23.6 S    0.9 |
            bitops-nsieve-bits-sunspider:     87.6 S     87.3 S   -0.3 |
         controlflow-recursive-sunspider:     43.0 S     43.2 S    0.5 |
                    crypto-aes-sunspider:    107.6 |    107.7 |        |
                    crypto-md5-sunspider:     93.0 |     93.3 |    0.3 |
                   crypto-sha1-sunspider:    132.0 |    132.1 |        |
             date-format-tofte-sunspider:    176.5 |    177.0 |    0.3 |
             date-format-xparb-sunspider:    181.6 |    182.1 |    0.3 |
                   math-cordic-sunspider:     77.3 |     77.4 |    0.1 |
             math-partial-sums-sunspider:    323.4 |    324.7 |    0.4 |
            math-spectral-norm-sunspider:     39.7 |     39.7 |        |
                    regexp-dna-sunspider:   1034.6 |   1034.5 |        |
                 string-base64-sunspider:    176.8 |    177.2 |    0.2 |
                  string-fasta-sunspider:    162.2 |    162.3 |        |
               string-tagcloud-sunspider:    304.6 |    304.9 |        |
            string-unpack-code-sunspider:    301.9 |    301.9 |        |
         string-validate-input-sunspider:    165.3 |    165.8 |    0.3 |
                               SunSpider:   4359.5 |   4366.1 |    0.2 |
---------------------------------------------------+----------+--------+
```
