### ISSUE TITLE
Check failed: trampoline_pos != kInvalidSlotPos.

### ISSUE THREAD

**Issue by andreas-schwab** [riscv-collab/v8#509]
During build of chromium, this error occurs:

<https://build.opensuse.org/package/live_build_log/openSUSE:Factory:RISCV/chromium/standard/riscv64>

python3 ../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/models/text_utils/text_utils-tsconfig.json --deps ../../core/common/bundle-tsconfig.json ../../core/platform/bundle-tsconfig.json ../../core/root/bundle-tsconfig.json --front_end_directory ../../third_party/devtools-frontend/src/front_end/models/text_utils --sources ../../third_party/devtools-frontend/src/front_end/models/text_utils/CodeMirrorUtils.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/ContentProvider.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/StaticContentProvider.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/Text.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextCursor.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextRange.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextUtils.ts

TypeScript compilation failed. Used tsconfig gen/third_party/devtools-frontend/src/front_end/models/text_utils/text_utils-tsconfig.json

#
# Fatal error in , line 0
# Check failed: trampoline_pos != kInvalidSlotPos.
#
#
#
#FailureMessage Object: 0x400f3d6d38
 1: 0x400077144a  [/usr/bin/node16]
 2: 0x40010de9d8 V8_Fatal(char const*, ...) [/usr/bin/node16]
 3: 0x4000e45b78 v8::internal::Assembler::bind_to(v8::internal::Label*, int) [/usr/bin/node16]
 4: 0x40010f0124 v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(v8::internal::compiler::DeoptimizationExit*) [/usr/bin/node16]
 5: 0x40010f3f4c v8::internal::compiler::CodeGenerator::AssembleCode() [/usr/bin/node16]
 6: 0x4001184630 v8::internal::compiler::PipelineImpl::AssembleCode(v8::internal::compiler::Linkage*, std::unique_ptr<v8::internal::AssemblerBuffer, std::default_delete<v8::internal::AssemblerBuffer> >) [/usr/bin/node16]
 7: 0x400118ee12 v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(v8::internal::RuntimeCallStats*, v8::internal::LocalIsolate*) [/usr/bin/node16]
 8: 0x400092602a v8::internal::OptimizedCompilationJob::ExecuteJob(v8::internal::RuntimeCallStats*, v8::internal::LocalIsolate*) [/usr/bin/node16]
 9: 0x4000945526 v8::internal::OptimizingCompileDispatcher::CompileNext(v8::internal::OptimizedCompilationJob*, v8::internal::LocalIsolate*) [/usr/bin/node16]
10: 0x400094579e v8::internal::OptimizingCompileDispatcher::CompileTask::RunInternal() [/usr/bin/node16]
11: 0x4000771752  [/usr/bin/node16]
12: 0x4003f23458  [/lib64/lp64d/libpthread.so.0]
13: 0x4003fe185e  [/lib64/lp64d/libc.so.6]

**Comment by luyahan** [comment]
Hi
What is your build commit id?

**Comment by qjivy** [comment]
It seems v8 abort for a runtime error.  But from this command line we can't judge how to retry  it.

```
python3 ../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/models/text_utils/text_utils-tsconfig.json --deps ../../core/common/bundle-tsconfig.json ../../core/platform/bundle-tsconfig.json ../../core/root/bundle-tsconfig.json --front_end_directory ../../third_party/devtools-frontend/src/front_end/models/text_utils --sources ../../third_party/devtools-frontend/src/front_end/models/text_utils/CodeMirrorUtils.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/ContentProvider.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/StaticContentProvider.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/Text.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextCursor.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextRange.ts ../../third_party/devtools-frontend/src/front_end/models/text_utils/TextUtils.ts

```

It will be help if you can provide more info about your build configuration, codebase.

**Comment by qjivy** [comment]
seems same error as https://github.com/riscv/v8/issues/350

**Comment by luyahan** [comment]
Hi @andreas-schwab  
I have submmit fixed patch to v8.
https://chromium-review.googlesource.com/c/v8/v8/+/3153835

**Comment by qjivy** [comment]
Resolved by

**Comment by qjivy** [comment]
Hi @andreas-schwab , we are happy to see that according to https://build.opensuse.org/package/show/openSUSE:Factory:RISCV/chromium, it seems that build is succeed.

Does that mean running a  Chromium browser on RISCV-64 is quite near?

**Comment by andreas-schwab** [comment]
It is completely untested, I would be surprised if it actually runs without crashing.  It would be nice if someone could test it.

**Comment by luyahan** [comment]
> It is completely untested, I would be surprised if it actually runs without crashing.  It would be nice if someone could test it.

![mmexport1632811408402.jpg](https://user-images.githubusercontent.com/22358871/135036547-43260c4c-651e-4ae4-9219-f8a63a06c93f.jpg)
intsall oepnsuse rpm on D1  openeuler

**Comment by andreas-schwab** [comment]
Thanks, that looks really good.

**Comment by lazyparser** [comment]
Congrats! 🎉 

Hopefully we will test it on Unmatched w/ AMD GPU.

**Comment by luyahan** [comment]
> It is completely untested, I would be surprised if it actually runs without crashing.  It would be nice if someone could test it.

Are you have a plan to upstreaming riscv64 patch of chromium？
