### ISSUE TITLE
Ask for the V8 gerrit CQ+2 permission for Lu Yahan

### ISSUE THREAD

**Issue by qjivy** [riscv-collab/v8#511]
Now Yahan could only  comment on the V8 RISC-V related  CLs on V8 gerrit. He can not make CQ+2.
Let's try to add his permission with CQ+2 and add him to  the owner list.
So both Yahan and me can review and make decision for code merge.
This would make the CI turn-green more effective.

**Comment by luyahan** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/3145370
