### ISSUE TITLE
Port Faster builtin/runtime/API calls (full solution)

### ISSUE THREAD

**Issue by luyahan** [riscv-collab/v8#512]
issue:
https://bugs.chromium.org/p/v8/issues/detail?id=11880

qiuji  15 minutes ago
https://docs.google.com/document/d/10qh2-b4C5OtSg-xLwyZpEI5ZihVBPtn1xwKBbQC26yI/edit

qiuji  15 minutes ago
这个你应该看过了，压缩指针的

qiuji  15 minutes ago
https://docs.google.com/document/d/1ry_QnFBahan78opn5auCgx0cfnkYapZtjOU9yjFaCmM/edit

qiuji  14 minutes ago
这个是关于开启压缩指针以后要把code object摆放紧凑一些的
New

qiuji  13 minutes ago
这个是去掉ApaterFrame的

qiuji  13 minutes ago
https://docs.google.com/document/d/15SQV4xOhD3K0omGJKM-Nn8QEaskH7Ir1VYJb9_5SjuM/edit#

qiuji  13 minutes ago
这个是去掉AdapterFrame后如何处理参数数量不匹配的：

qiuji  13 minutes ago
https://docs.google.com/document/d/156nh17BpyLNmDmONyC_ZQUbi0h6goNysds2DLXcAzVc/preview

qiuji  12 minutes ago
这个是快速FastAPIcall的：

qiuji  12 minutes ago
https://docs.google.com/document/d/1vjddeZw9HmAWOy2pkJtDOW0KtAueLpvGlY1od-uijd0/edit#heading=h.n1atlriavj6v

**Comment by qjivy** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/3257964

**Comment by qjivy** [comment]
Seemed we have porting the related upstream changes. Close it.
