### ISSUE TITLE
Check failed: fixed_size_above_fp + (stack_slots * kSystemPointerSize) - CommonFrameConstants::kFixedFrameSizeAboveFp + outgoing_size == result.

### ISSUE THREAD

**Issue by andreas-schwab** [riscv-collab/v8#513]
When running chromium from <https://build.opensuse.org/package/show/home:Andreas_Schwab:riscv:chromium/chromium> (which uses 9.4.146.21) this error occurs:

#
# Fatal error in , line 0
# Check failed: fixed_size_above_fp + (stack_slots * kSystemPointerSize) - CommonFrameConstants::kFixedFrameSizeAboveFp + outgoing_size == result.
#
#
#
#FailureMessage Object: 0x3fd9d76f70#0 0x002ab58669ca (/usr/lib64/chromium/chrome+0x598b9c9)
#1 0x002ab57ca914 (/usr/lib64/chromium/chrome+0x58ef913)
#2 0x002ab8709c0a (/usr/lib64/chromium/chrome+0x882ec09)
#3 0x002ab695b80a (/usr/lib64/chromium/chrome+0x6a80809)
#4 0x002ab3bdcda6 (/usr/lib64/chromium/chrome+0x3d01da5)
#5 0x002ab3bdb326 (/usr/lib64/chromium/chrome+0x3d00325)
#6 0x002ab4406de0 (/usr/lib64/chromium/chrome+0x452bddf)

**Comment by luyahan** [comment]
Hi @andreas-schwab  what does " running chromium" mean?  Are you open a html on chrome?

**Comment by andreas-schwab** [comment]
The openSUSE chromium package  is configured to open https://search.opensuse.org/ and https://www.google.com/chrome/ on the first run.  Both tabs will crash in the same way.
