### ISSUE TITLE
webpack-make from cockpit crashes with v8 9.8

### ISSUE THREAD

**Issue by andreas-schwab** [riscv-collab/v8#520]
https://build.opensuse.org/package/live_build_log/home:Andreas_Schwab:riscv:node/cockpit/standard/riscv64

This is with the upcoming node v18, which uses 9.8.177.9.

NODE_ENV=production SRCDIR=/home/abuild/rpmbuild/BUILD/cockpit-251.3 ./tools/webpack-make -d dist/base1/Makefile.deps -c ./webpack.config.js
NODE_ENV=production SRCDIR=/home/abuild/rpmbuild/BUILD/cockpit-251.3 ./tools/webpack-make -d dist/apps/Makefile.deps -c ./webpack.config.js
NODE_ENV=production SRCDIR=/home/abuild/rpmbuild/BUILD/cockpit-251.3 ./tools/webpack-make -d dist/kdump/Makefile.deps -c ./webpack.config.js
NODE_ENV=production SRCDIR=/home/abuild/rpmbuild/BUILD/cockpit-251.3 ./tools/webpack-make -d dist/metrics/Makefile.deps -c ./webpack.config.js
make[1]: *** [Makefile:9859: dist/base1/manifest.json] Segmentation fault
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:9859: dist/apps/manifest.json] Segmentation fault
make[1]: *** [Makefile:9859: dist/kdump/manifest.json] Segmentation fault
make[1]: *** [Makefile:9859: dist/metrics/manifest.json] Segmentation fault

**Comment by luyahan** [comment]
may be this pr  can  fix this
https://github.com/nodejs/node/pull/42067

**Comment by andreas-schwab** [comment]
I have already added that patch, it doesn't make a difference.

https://build.opensuse.org/package/view_file/home:Andreas_Schwab:riscv:node/nodejs18/riscv.patch

**Comment by luyahan** [comment]
I try to build cockpit 
it happens:
```
[    1s] processing recipe /root/home:Andreas_Schwab:riscv:node/cockpit/cockpit.spec ...
[    1s] unknown keyword in config: repourl:
[    1s] unknown keyword in config: registryurl:
[    1s] running changelog2spec --target rpm --file /root/home:Andreas_Schwab:riscv:node/cockpit/cockpit.spec
[    1s] init_buildsystem --configdir /usr/lib/build/configs --cachedir /var/cache/build --rpmlist /tmp/rpmlist.2b9r2hj4 /root/home:Andreas_Schwab:riscv:node/cockpit/cockpit.spec ...
[    1s] registering binfmt handlers for cross build
[    1s] mount: /proc: Permission denied
[    1s] /usr/lib/build/init_buildsystem: line 628: /proc/sys/vm/mmap_min_addr: Read-only file system
[    1s] unknown keyword in config: repourl:
[    1s] unknown keyword in config: registryurl:
[    1s] mount: /var/tmp/build-root/standard-riscv64/proc: cannot mount none read-only.
[    1s] Could not mount /proc, is this a container with missing capabilities?
[    1s]
[    1s]  failed "build cockpit.spec" at Wed Mar  2 06:23:46 UTC 2022.
[    1s]

The buildroot was: /var/tmp/build-root/standard-riscv64
```

I run `osc -A https://api.opensuse.org checkout  home:Andreas_Schwab:riscv:node/cockpit` `osc build`  in opensuse/leap with docker

**Comment by luyahan** [comment]
> NODE_ENV=production SRCDIR=/home/abuild/rpmbuild/BUILD/cockpit-251.3 ./tools/webpack-make -d dist/kdump/Makefile.deps -c ./webpack.config.js

I enter sandbox and run node -v
```
abuild@2726c9381c7f:/home/abuild/rpmbuild/BUILD/cockpit-251.3> node -v
v17.5.0
```
node version is node v18.0.0-pre.
And v17.5.0 node is not merge fix patch

**Comment by luyahan** [comment]
> I have already added that patch, it doesn't make a difference.
> 
> https://build.opensuse.org/package/view_file/home:Andreas_Schwab:riscv:node/nodejs18/riscv.patch

May be you should merge patch into https://build.opensuse.org/package/show/home:Andreas_Schwab:riscv:node/nodejs17

**Comment by andreas-schwab** [comment]
Sorry, I made an error in the project settings.  Please try again.

**Comment by luyahan** [comment]
> Sorry, I made an error in the project settings. Please try again.

This cl to fix this issue:https://chromium-review.googlesource.com/c/v8/v8/+/3503170

**Comment by luyahan** [comment]
Build pass
