### ISSUE TITLE
cctest test-macro-assembler-riscv32/macro_float_minmax_f32(64) fails on native test mode

### ISSUE THREAD

**Issue by qjivy** [riscv-collab/v8#668]
cmd line:

```
./out/riscv32.native.release/cctest test-macro-assembler-riscv32/macro_float_minmax_f32 --random-seed=1418596419 --nohard-abort --testing-d8-test-runner
./out/riscv32.native.release/cctest test-macro-assembler-riscv32/macro_float_minmax_f64 --random-seed=1418596419 --nohard-abort --testing-d8-test-runner
```

**Comment by luyahan** [comment]
test-macro-assembler-riscv32/macro_float_minmax_f32
run test in debug pass

**Comment by luyahan** [comment]
use clang 15.0.0 build pass

**Comment by luyahan** [comment]
f64:
<img width="676" alt="截屏2022-06-17 10 37 25" src="https://user-images.githubusercontent.com/22358871/174213877-4aa36b9c-7fd2-43a5-beab-320af39c5138.png">


0x40ac92bc <Testmacro_float_minmax_f64()+484>   sw      zero,-168(s0)                                                              │
│   0x40ac92c0 <Testmacro_float_minmax_f64()+488>   sw      zero,-164(s0)                                                              │
│  >0x40ac92c4 <Testmacro_float_minmax_f64()+492>   fsd     fs0,-160(s0) 

fs0  don't been initialized correctly

**Comment by luyahan** [comment]
clang 
<img width="564" alt="截屏2022-06-17 10 43 15" src="https://user-images.githubusercontent.com/22358871/174218079-179dcf89-da85-485d-96d4-94b941f9e1ad.png">
